spring:
  application:
    name: happypay-money-service
  jackson:
    time-zone: Asia/Seoul
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: none # DB 초기화 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate:
        auto_quote_keyword: false
        globally_quoted_identifiers: false
        format_sql: true     # 쿼리 로그 포맷 (정렬)
        show_sql: true       # 쿼리 로그 출력
        jdbc:
          time_zone: Asia/Seoul
  kafka:
    group-id: money-service
    bootstrap-servers: [ "localhost:29094" ]
task:
  recharge-topic: happypay.task.recharge
  recharge-result-topic: happypay.task.recharge.result
  firm-banking-topic: happypay.task.firmbanking
  firm-banking-result-topic: happypay.task.firmbanking.result
logging:
  topic: happypay.logging.out.stdout
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE
axon:
  axonserver:
    servers: localhost:18124
  serializer:
    events: jackson
    messages: jackson
    general: xstream