apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: msa-pay
resources:
  - membership-service-pod.yaml
namespace: dev
namePrefix: dev-
nameSuffix: -v1

# 이미지 변경
images:
  - name: membership-service
    newName: nginx
    newTag: 1.19.1

configMapGenerator:
  - name: dev-config
    files:
      - app-dev.properties
secretGenerator:
  - name: dev-secret
    envs:
      - secrets-dev.env