spring:
  datasource:
    url: jdbc:mysql://mysql:3306/banking?serverTimezone=UTC&characterEncoding=UTF-8
    username: local
    password: local
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: [ "kafka:9092" ]
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        show_sql: false
axon:
  axonserver:
    servers: axon-server:8124
service:
  membership:
    url: http://membership-service:8080
