apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: dev-membership-service
resources:
  - ../../base
namespace: dev
namePrefix: dev

labels:
  - pairs:
      env: dev

patches:
  - path: deploy-replicas.yaml
  - target:
      kind: Ingress
      name: membership-service-ingress
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: dev.membership-service.com