apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: membership-service
resources:
  - membership-service-deploy.yaml
  - membership-service-svc.yaml
  - membership-service-ingress.yaml
labels:
  - pairs:
      config: kustomize
